# Generated by Django 5.2 on 2025-04-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
