# Generated by Django 5.2 on 2025-04-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0002_alter_message_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='knowledgebase',
            name='aichat_know_questio_4ff348_idx',
        ),
    ]
