# Generated by Django 5.2 on 2025-04-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0003_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['question_pattern'], name='aichat_know_questio_4ff348_idx'),
        ),
    ]
